/**
 * Scope descriptor for a single agent execution context.
 * Provides the working directory, path allowlist, and optional context hints
 * needed for tool execution and LLM context injection.
 * The calling layer is responsible for translating domain-specific concepts
 * into these generic path-based fields.
 */
export interface ExecutionScope {
  /** Working directory for shell tools and the agent's spatial anchor. */
  workingDirectory: string;
  /** Path allowlist enforced by PermissionSandbox before any tool call. */
  allowedPaths: string[];
  /** Files/dirs the user currently selected — boosted in LLM context priority. */
  focusedPaths?: string[];
  /**
   * Short human-readable hint injected verbatim into the LLM system prompt.
   * Generated by the product layer; may include product-specific vocabulary.
   * KyberKit passes it through without interpreting it.
   */
  scopeHint?: string;
}
