/**
 * A standardised signal emitted when the user judges agent output.
 * The Harness defines structure; the calling layer fills in semantics.
 * No Kevin product types here — only generic signal fields.
 */
export interface FeedbackSignal {
  signal_type: 'accepted' | 'rejected' | 'modified' | 'redo';
  /** Human-readable context generated by the calling layer. */
  signal_context: string;
  /** 0.0 (weak signal) → 1.0 (strong signal). */
  strength: number;
  metadata?: Record<string, unknown>;
}
